accounts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import * 
from django.contrib.auth.models import User

app_name = 'accounts'
urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^about/$', about, name='about'),
    url(r'^sign_in/$', sign_in, name='sign_in'),
    url(r'^upload_track/$', upload_track_page, name='upload_track_page'),
    url(r'^api/reg_user/$', reg_user, name='reg_user'),
    url(r'^api/upload_track/$', upload_track, name='upload_track'),
    url(r'^api/getplaylist/$', getplaylist, name='getplaylist'),
]

albums/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import * 
from django.contrib.auth.models import User

app_name = 'albums'
urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^about/$', about, name='about'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include("accounts.urls", namespace='accounts')),
]

playlist/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import * 
from django.contrib.auth.models import User

app_name = 'playlist'
urlpatterns = [
    url(r'^$', main, name='main'),
    url(r'^about/$', about, name='about'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

def upload_location(instance, filename):
    ProfileModel = instance.__class__
    if ProfileModel.objects.order_by("id").last():
        new_id = ProfileModel.objects.order_by("id").last().id + 1
    return "%s" %(filename)
 
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE,related_name='profile')
    name = models.TextField(blank = True,null = True,default='name')
    mail = models.TextField(blank = True,null = True,default='mail')
    image = models.ImageField(upload_to=upload_location, blank = True,null = True)

albums/models.py
from django.db import models
from django.contrib.auth.models import User

def upload_location(instance, filename):
    AlbumModel = instance.__class__
    if AlbumModel.objects.order_by("id").last():
        new_id = AlbumModel.objects.order_by("id").last().id + 1
    return "%s" %(filename)

class Album(models.Model):
    name = models.TextField(blank = True,null = True,default='name')
    description = models.TextField(blank = True,null = True,default='mail')
    image = models.ImageField(upload_to=upload_location, blank = True,null = True)

playlist/models.py
from django.db import models
from django.contrib.auth.models import User

def upload_location(instance, filename):
    ProfileModel = instance.__class__
    if ProfileModel.objects.order_by("id").last():
        new_id = ProfileModel.objects.order_by("id").last().id + 1
    return "%s" %(filename)
 
class Playlist(models.Model):
    name = models.TextField(blank = True,null = True,default='My Playlist')
    image = models.ImageField(upload_to=upload_location, blank = True,null = True)
    listenings = models.IntegerField(blank = True,null = True,default=0)

class Track(models.Model):
    name = models.TextField(blank = True,null = True,default='My Song')
    artist = models.TextField(blank = True,null = True,default='My Artist')
    file = models.FileField(default='')
    listenings = models.IntegerField(blank = True,null = True,default=0)

accounts/views.py
from django.shortcuts import render

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.http import JsonResponse
from playlist.models import Playlist, Track

def main(request):
    like = 0
    like = like + 1
    context = {
        "land_type":"about",
        "name": "arsen",
    }
    return render(request, "main.html", context)
    
def about(request):
    context = {
    }
    return render(request, "playlist.html", context)

def sign_in(request):
    context = {
    }
    return render(request, "sign_in.html", context)

def upload_track_page(request):
    context = {
    }
    return render(request, "create_track.html", context)
    
def reg_user(request):
    name = request.GET.get("mail")
    Playlist.objects.create(name=name)
    data = {
    }
    return JsonResponse(data)

def upload_track(request):
    song_name = request.POST.get("song_name")
    artist = request.POST.get("artist")
    link = request.POST.get("link")
    track = Track.objects.create(
        name=song_name,
        artist=artist,
        )
    if request.FILES.get('file'):
        file = request.FILES.get('file')
        track.file = file
        track.save()
    data = {
        "ok":"VSE POLUCHILOSЬ"
    }
    return JsonResponse(data)


def getplaylist(request):
    tracks = Track.objects.all()
    data_music = []
    for i in range(0, len(tracks)):
        track = tracks[i]
        if track.file:
            file_url = track.file.url
        else:
            file_url = ""
        data_music.append([track.artist, track.name, file_url])
    data = {
        "data_music":data_music,
    }
    return JsonResponse(data)

albums/views.py
from django.shortcuts import render

def main(request):
    like = 0
    like = like + 1
    context = {
        "land_type":"about",
        "name": "arsen",
        "id": 6,
    }
    return render(request, "index.html", context)
    
def about(request):
    context = {
        "id": 6,
    }
    return render(request, "about.html", context)
    

playlist/views.py
from django.shortcuts import render

def main(request):
    like = 0
    like = like + 1
    context = {
        "land_type":"about",
        "name": "arsen",
        "id": 6,
    }
    return render(request, "index.html", context)
    
def about(request):
    context = {
        "id": 6,
    }
    return render(request, "playlist.html", context)
    

frontend/templates/audio.html
{% load static %}
<div id="original_audio">
	<span class="artist_name"></span>
	-
	<span class="song_name"></span>
	<br><br>
	<div>
		<audio controls>
		  <source class="audio_source" src="" type="audio/mpeg">
			Your browser does not support the audio element.
		</audio>
	</div>	
</div>

frontend/templates/create_track.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="image_box" id="main_info">
	<div class="mt50">
		<div class="large_text mt15 mb15">Spotify</div>		
		<div class="mb15">
			<div><b>Song name</b></div>
			<input id="song_name_input" type="text" name="">	
		</div>
		<div class="mb15">
			<div><b>Artist name</b></div>
			<input id="artist_input" type="text" name="">
		</div>		
		<div class="mb15">
			<div><b>MP3 file</b></div>
            <label>
			    <input id="upload_input" type="file" class="hidden" required/>
			    <a class="btn btn-white">Select file</a>
			</label>
		</div>		
		<div class="mt30">
			<a class="btn-green btn mt15" onclick="upload_track()">Upload</a>
		</div>	
	</div>
</div>
{% endblock content %}

frontend/templates/header.html
<div class="dflex header">
	<a class="link" href="{% url 'accounts:main' %}">Music Triangle</a>
	<a class="link" href="{% url 'accounts:about' %}">Playlist</a>
	<a class="link" href="{% url 'accounts:upload_track_page' %}">Upload track</a>
	<a class="link link_right" href="{% url 'accounts:sign_in' %}">Sign In</a>
</div>

frontend/templates/index.html
{% load static %}
<html>
<head>
	<title>Music blog</title>
 	<link rel='stylesheet' href='{% static "style/style.css" %}'/>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
</head>
<body>
	{% include "header.html" %}
	{% block content %}{% endblock content %}	
	<span class="csrf hidden" csrf="{{ csrf_token }}"></span>
	<script type="text/javascript" src="{% static 'scripts/script.js' %}"></script>
</body>
</html>

frontend/templates/main.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="dflex bg_blue pd" id="main_info">
	<div class="half_w">
		<h1>My music Blog</h1>
		<h2>
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
		</h2>
	</div>
	<div class="half_w image_box">
		<img class="small_img" src="{% static 'images/bird.png' %}">		
	</div>		
</div>
<div class="dflex bg_red pd" id="second_info">
	<div class="half_w image_box">
		<img class="small_img" src="{% static 'images/bird.png' %}">		
	</div>		
	<div class="half_w">
		<h1>My music Blog</h1>
		<h2>
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
		</h2>
	</div>
</div>
<div class="dflex bg_yellow pd" id="third_info">
	<div class="card" >
		<div class="card_img">
			<h1 class="card_hidden_text" style="display: none;">YO</h1>
		</div>
		<div>
			<h2 class="card_header">Popular</h2>
			<h4 class="card_text">jfwjrnk kefnjev kefnkev ekrnjfkjn </h4>
		</div>
	</div>
</div>

<div class="bg_blue pd" id="js_block">
	<button class="btn" onclick="get_data()">Get data</button>
</div>
{% endblock content %}

frontend/templates/playlist.html
{% load static %}
<html>
<head>
	<title>Playlist</title>
 	<link rel='stylesheet' href='{% static "style/style.css" %}'/>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Ceviche+One&family=Fruktur&display=swap" rel="stylesheet">	
</head>
<body>
	{% include "header.html" %}
	<div class="dflex bg_blue pd" id="main_info">
		<div style="display:none;">
			{% include "audio.html" %}
		</div>
		<div id="music_box">
		</div>
	</div>
	<script type="text/javascript" src="{% static 'scripts/script.js' %}"></script>
</body>
</html>

frontend/templates/sign_in.html
{% load static %}

<html>
<head>
	<title>Music blog</title>
 	<link rel='stylesheet' href='{% static "style/style.css" %}'/>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Ceviche+One&family=Fruktur&display=swap" rel="stylesheet">	
</head>
<body>
	{% include "header.html" %}
	<div class="image_box">
		<div>
			<div class="large_text mt50">Spotify</div>
			<div class="mb15">
				<div><b>Mail</b></div>
				<input id="mail_input" type="text" name="">
			</div>
			<div class="mb15">
				<div><b>Password</b></div>
				<input id="password_input" type="password" name="">			
			</div>		
			<div>
				<button class="btn" onclick="send_data()">Sign in</button>
			</div>	
		</div>
	</div>
	<script type="text/javascript" src="{% static 'scripts/script.js' %}"></script>
</body>
</html>

static_cdn/templates/audio.html
{% load static %}
<div id="original_audio">
	<span class="artist_name"></span>
	-
	<span class="song_name"></span>
	<br><br>
	<div>
		<audio controls>
		  <source class="audio_source" src="" type="audio/mpeg">
			Your browser does not support the audio element.
		</audio>
	</div>	
</div>

static_cdn/templates/create_track.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="image_box">
	<div class="mt50">
		<div class="large_text mt15 mb15">Spotify</div>		
		<div class="mb15">
			<div><b>Song name</b></div>
			<input id="song_name_input" type="text" name="">	
		</div>
		<div class="mb15">
			<div><b>Artist name</b></div>
			<input id="artist_input" type="text" name="">
		</div>		
		<div class="mb15">
			<div><b>Link</b></div>
			<input id="link_input" type="text" name="">	
		</div>		
		<div>
			<button class="btn mt15" onclick="upload_track()">Upload</button>
		</div>	
	</div>
</div>
{% endblock content %}

static_cdn/templates/header.html
<div class="dflex header">
	<a class="link" href="{% url 'accounts:main' %}">Music Triangle</a>
	<a class="link" href="{% url 'accounts:about' %}">Playlist</a>
	<a class="link" href="{% url 'accounts:upload_track_page' %}">Upload track</a>
	<a class="link link_right" href="{% url 'accounts:sign_in' %}">Sign In</a>
</div>

static_cdn/templates/index.html
{% load static %}
<html>
<head>
	<title>Music blog</title>
 	<link rel='stylesheet' href='{% static "style/style.css" %}'/>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
</head>
<body>
	{% include "header.html" %}
	{% block content %}{% endblock content %}	
	<script type="text/javascript" src="{% static 'scripts/script.js' %}"></script>
</body>
</html>

static_cdn/templates/main.html
{% extends "index.html" %}
{% load static %}
{% block content %}
<div class="dflex bg_blue pd" id="main_info">
	<div class="half_w">
		<h1>My music Blog</h1>
		<h2>
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
		</h2>
	</div>
	<div class="half_w image_box">
		<img class="small_img" src="{% static 'images/bird.png' %}">		
	</div>		
</div>
<div class="dflex bg_red pd" id="second_info">
	<div class="half_w image_box">
		<img class="small_img" src="{% static 'images/bird.png' %}">		
	</div>		
	<div class="half_w">
		<h1>My music Blog</h1>
		<h2>
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
			WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548 WIEUfnejwfsdvldknsfdg5548
		</h2>
	</div>
</div>
<div class="dflex bg_yellow pd" id="third_info">
	<div class="card" >
		<div class="card_img">
			<h1 class="card_hidden_text" style="display: none;">YO</h1>
		</div>
		<div>
			<h2 class="card_header">Popular</h2>
			<h4 class="card_text">jfwjrnk kefnjev kefnkev ekrnjfkjn </h4>
		</div>
	</div>
</div>

<div class="bg_blue pd" id="js_block">
	<button class="btn" onclick="get_data()">Get data</button>
</div>
{% endblock content %}

static_cdn/templates/playlist.html
{% load static %}
<html>
<head>
	<title>Playlist</title>
 	<link rel='stylesheet' href='{% static "style/style.css" %}'/>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Ceviche+One&family=Fruktur&display=swap" rel="stylesheet">	
</head>
<body>
	{% include "header.html" %}
	<div class="dflex bg_blue pd" id="main_info">
		<div style="display:none;">
			{% include "audio.html" %}
		</div>
		<div id="music_box">
			{% include "audio.html" %}
			{% include "audio.html" %}
		</div>
	</div>
	<script type="text/javascript" src="{% static 'scripts/script.js' %}"></script>
</body>
</html>

static_cdn/templates/sign_in.html
{% load static %}

<html>
<head>
	<title>Music blog</title>
 	<link rel='stylesheet' href='{% static "style/style.css" %}'/>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Ceviche+One&family=Fruktur&display=swap" rel="stylesheet">	
</head>
<body>
	{% include "header.html" %}
	<div class="image_box">
		<div>
			<div class="large_text mt50">Spotify</div>
			<div class="mb15">
				<div><b>Mail</b></div>
				<input id="mail_input" type="text" name="">
			</div>
			<div class="mb15">
				<div><b>Password</b></div>
				<input id="password_input" type="password" name="">			
			</div>		
			<div>
				<button class="btn" onclick="send_data()">Sign in</button>
			</div>	
		</div>
	</div>
	<script type="text/javascript" src="{% static 'scripts/script.js' %}"></script>
</body>
</html>